import racingImage from "@/assets/game-racing.jpg";
import actionImage from "@/assets/game-action.jpg";
import puzzleImage from "@/assets/game-puzzle.jpg";
import ioImage from "@/assets/game-io.jpg";
import neonRiptideImage from "@/assets/cover-action-neon-riptide.jpg";
export type Category =
  | "Экшен"
  | "Приключения"
  | "Аркадные"
  | "Настольные"
  | "Карточные"
  | "Кликеры"
  | "Гонки"
  | ".io"
  | "Головоломки"
  | "Стрелялки"
  | "Симуляторы"
  | "Спорт"
  | "Стратегии"
  | "Викторины"
  | "Слова";

export type Game = {
  slug: string;
  title: string;
  category: Category;
  tags: string[];
  description: string;
  controls: string[];
  image: string;
  rating: number;
  plays: number;
  year: number;
  badge?: "ХИТ" | "НОВОЕ" | "ТОП";
  accent: "lime" | "cyan" | "coral";
};

export const games: Game[] = [
  {
    slug: "neon-drift",
    title: "Neon Drift",
    category: "Гонки",
    tags: ["машины", "дрифт", "3D"],
    description:
      "Ночные заезды по неоновому мегаполису. Дрифтуйте в миллиметрах от соперников и собирайте нитро.",
    controls: ["WASD — движение", "Пробел — ручной тормоз", "Shift — нитро"],
    image: racingImage,
    rating: 4.9,
    plays: 12800000,
    year: 2026,
    badge: "ХИТ",
    accent: "lime",
  },
  {
    slug: "skyline-raider",
    title: "Skyline Raider",
    category: "Приключения",
    tags: ["паркур", "экшен", "герой"],
    description:
      "Покоряйте летающий город с крюком-кошкой и пробирайтесь через головокружительные уровни.",
    controls: ["WASD — движение", "Мышь — прицел", "E — крюк"],
    image: actionImage,
    rating: 4.8,
    plays: 7600000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "prism-shift",
    title: "Prism Shift",
    category: "Головоломки",
    tags: ["логика", "порталы", "блоки"],
    description:
      "Меняйте гравитацию, соединяйте кристаллы и открывайте порталы в футуристической лаборатории.",
    controls: ["Мышь — выбор", "R — перезапуск", "Z — отмена"],
    image: puzzleImage,
    rating: 4.7,
    plays: 4200000,
    year: 2026,
    badge: "ТОП",
    accent: "cyan",
  },
  {
    slug: "hover-arena",
    title: "Hover Arena",
    category: ".io",
    tags: ["мультиплеер", "арена", "гонки"],
    description:
      "Соревнуйтесь на воздушных аренах, сталкивайте соперников и останьтесь последним пилотом.",
    controls: ["WASD — движение", "Мышь — камера", "Пробел — ускорение"],
    image: ioImage,
    rating: 4.6,
    plays: 9100000,
    year: 2026,
    badge: "ХИТ",
    accent: "coral",
  },
  {
    slug: "strike-point",
    title: "Strike Point",
    category: "Стрелялки",
    tags: ["FPS", "тактика", "онлайн"],
    description:
      "Быстрые тактические матчи на компактных аренах с точной стрельбой и мгновенным стартом.",
    controls: ["WASD — движение", "Мышь — прицел", "R — перезарядка"],
    image: actionImage,
    rating: 4.5,
    plays: 6500000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "turbo-league",
    title: "Turbo League",
    category: "Спорт",
    tags: ["футбол", "машины", "аркада"],
    description:
      "Футбол на реактивных машинах: забивайте с воздуха и защищайте ворота вместе с командой.",
    controls: ["Стрелки — движение", "X — прыжок", "C — ускорение"],
    image: racingImage,
    rating: 4.7,
    plays: 5900000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "block-bloom",
    title: "Block Bloom",
    category: "Аркадные",
    tags: ["блоки", "релакс", "комбо"],
    description: "Собирайте сияющие фигуры в линии и создавайте длинные цепочки комбо без таймера.",
    controls: ["Мышь — перемещение", "Клик — разместить", "Esc — пауза"],
    image: puzzleImage,
    rating: 4.4,
    plays: 3800000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "zero-zone",
    title: "Zero Zone",
    category: "Экшен",
    tags: ["выживание", "арена", "волны"],
    description: "Отбивайтесь от волн дронов, комбинируйте оружие и продержитесь до эвакуации.",
    controls: ["WASD — движение", "Мышь — атака", "1–3 — оружие"],
    image: ioImage,
    rating: 4.6,
    plays: 8100000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "circuit-sprint",
    title: "Circuit Sprint",
    category: "Гонки",
    tags: ["скорость", "тайм-атак", "аркада"],
    description: "Короткие техничные трассы, призрачные соперники и борьба за сотые доли секунды.",
    controls: ["WASD — движение", "Shift — нитро", "R — рестарт"],
    image: racingImage,
    rating: 4.3,
    plays: 2700000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "portal-paws",
    title: "Portal Paws",
    category: "Приключения",
    tags: ["платформер", "головоломка", "кот"],
    description:
      "Помогите космическому коту вернуться домой, прыгая между измерениями и собирая звёзды.",
    controls: ["Стрелки — движение", "Пробел — прыжок", "E — портал"],
    image: puzzleImage,
    rating: 4.8,
    plays: 3400000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "goal-rush",
    title: "Goal Rush",
    category: "Спорт",
    tags: ["футбол", "пенальти", "быстрая"],
    description: "Серия пенальти с идеальной физикой удара. Читайте вратаря и попадайте в девятку.",
    controls: ["Мышь — направление", "Удержание — сила", "Пробел — удар"],
    image: ioImage,
    rating: 4.2,
    plays: 2100000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "pixel-frontier",
    title: "Pixel Frontier",
    category: "Симуляторы",
    tags: ["крафт", "исследование", "пиксели"],
    description: "Исследуйте уютный бесконечный мир, собирайте ресурсы и стройте собственную базу.",
    controls: ["WASD — движение", "Мышь — действие", "I — инвентарь"],
    image: actionImage,
    rating: 4.5,
    plays: 4700000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-01",
    title: "Неоновый Прибой",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Оседлайте штормовые волны, соединяйте воздушные трюки и возвращайте затопленный город у духов течения.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: neonRiptideImage,
    rating: 4.4,
    plays: 1781000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-02",
    title: "Пепельный Свод",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Пробирайтесь через вулканические руины, чтобы посадить последнюю живую звезду до пробуждения кратера.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.5,
    plays: 1918000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-03",
    title: "Небесный Крюк",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Раскачивайтесь между воздушными поездами, спасайте пассажиров и обгоняйте громовых китов в бурном небе.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.6,
    plays: 2055000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "action-04",
    title: "Моховой Клинок",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Преследуйте сбежавшее семенное ядро в храме джунглей, где древние машины цветут опасными лозами.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.7,
    plays: 2192000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-05",
    title: "Призматическая Осада",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Превращайте вражеский огонь в ослепительные трассы, защищая крепость из солнечных зеркал.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.8,
    plays: 2329000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-06",
    title: "Дрейфующий Фонарь",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Скользите по призрачным льдам, чертя защитные знаки до того, как лунный город заледенеет.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.9,
    plays: 2466000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "action-07",
    title: "Железный Сад",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Собирайте металлические плоды и защищайте сад от стальных насекомых, размножающихся на рассвете.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.1,
    plays: 2603000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-08",
    title: "Бегущий Сквозь Завесу",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Доставляйте запретные воспоминания по меняющимся крышам, осваивая портальные складки и призрачную погоню.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.2,
    plays: 2740000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-09",
    title: "Приливная Кузня",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Чините разумную подлодку прямо в бою, а затем ведите её через желоба свирепых течений.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.3,
    plays: 2877000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "action-10",
    title: "Солнечная Спираль",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Вращайте солнечный бич во время затмения, рушьте гигантские дюны до того, как они погребут караван.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.4,
    plays: 3014000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-11",
    title: "Цветочный Контур",
    category: "Экшен",
    tags: ["экшен", "новая игра"],
    description:
      "Выращивайте электрические цветы-бастионы и направляйте ток через оживлённый рынок под непрерывным дождём.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.5,
    plays: 3151000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-01",
    title: "Картограф приливного стекла",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Исследуйте затопленные обсерватории и раскройте тайну исчезнувшей цивилизации, наносившей на карты живое море.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.6,
    plays: 3288000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-02",
    title: "Сад углей",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description: "Выращивайте огненные сады и защищайте редкий урожай от пробуждающегося вулкана.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.7,
    plays: 3425000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-03",
    title: "Кочевник лунной магистрали",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Странствуйте по лунной железной дороге между невозможными станциями, выторговывая путь домой.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.8,
    plays: 3562000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-04",
    title: "Эхо-фонарь",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description: "Доставьте живое послание через каньоны, где каждый звук меняет дорогу впереди.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.9,
    plays: 3699000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-05",
    title: "Воздушный змей морозного ветра",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Покоряйте ледяные скалы и направляйте сияющего воздушного змея, спасая небесных китов.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.1,
    plays: 3836000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-06",
    title: "Пробуждение корней",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Возродите древнего стража джунглей, разгадывая тайны растений под забытым храмом.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.2,
    plays: 3973000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-07",
    title: "Заводная крачка",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Проведите отважную механическую птицу через подводные крепости и найдите компас создателя бурь.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.3,
    plays: 4110000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-08",
    title: "Призматическое хранилище",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Пробирайтесь по преломляющим свет пещерам и освободите украденный звёздный свет до вечного запечатывания.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.4,
    plays: 4247000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-09",
    title: "Пыльный хор",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Возглавьте призрачный хор в пустыне и пробудите город, погребённый веками молчания.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.5,
    plays: 4384000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-10",
    title: "Хранители мохового света",
    category: "Приключения",
    tags: ["приключения", "новая игра"],
    description:
      "Пронесите хрупкий маяк через грибные глубины, чтобы разбудить гору, защищающую долину.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.6,
    plays: 4521000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-01",
    title: "Облачный курьер",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description:
      "Доставляйте заряженные облачные посылки по крышам, пока буря не сомкнула маршрут.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.7,
    plays: 4658000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-02",
    title: "Жемчужный захват",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Хватайте светящиеся жемчужины и ускользайте от рушащегося морского дна.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.8,
    plays: 4795000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "arcade-03",
    title: "Ветровая спираль",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description:
      "Вместе с ветровым змеем собирайте воздушные кольца в самую длинную небесную серию.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.9,
    plays: 4932000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-04",
    title: "Искра шестерён",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Мчитесь по движущимся механизмам фабрики, выверяя каждый прыжок сквозь искры.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.1,
    plays: 5069000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-05",
    title: "Приливный прыгун",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Прыгайте по гигантским грибам, пока лиловый прилив стирает дорогу.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.2,
    plays: 5206000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "arcade-06",
    title: "Грозовой звон",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Звоните в небесные колокола в ритм, направляя хрупкий дирижабль сквозь джунгли.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.3,
    plays: 5343000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-07",
    title: "Скользящий полярный свет",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Скользите по ледяным крышам и рисуйте сияющие северные огни до рассвета.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.4,
    plays: 5480000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-08",
    title: "Солнечный перекат",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description: "Катите хрустальное солнце по зыбким дюнам, перехитряя миражных зверей.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.5,
    plays: 5617000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "arcade-09",
    title: "Ловец угольков",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description:
      "Перепрыгивайте через вулканическую арену и ловите падающие угольки для дополнительного жара.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.6,
    plays: 5754000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-10",
    title: "Орбитальный сад",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description:
      "Сажайте семенные сферы на астероидах, соединяя цветущие созвездия до сбоя гравитации.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.7,
    plays: 5891000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-11",
    title: "Призматическое крыло",
    category: "Аркадные",
    tags: ["аркадные", "новая игра"],
    description:
      "Перенаправляйте лучи через гигантские кристаллы, пробуждая тайный луг за собором.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.8,
    plays: 6028000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-01",
    title: "Совет Приливного Стекла",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Договаривайтесь о течениях, союзах и редком солнечном свете, чтобы развить подводный район.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.9,
    plays: 6165000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-02",
    title: "Фонарный Сад",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Выращивайте зачарованные деревья, направляйте духов и успейте собрать урожай до рассвета.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.1,
    plays: 6302000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-03",
    title: "Железные Воздушные Змеи",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Прокладывайте смелые курьерские маршруты над парящим городом, пока ветер и погода меняются.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.2,
    plays: 6439000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-04",
    title: "Моховой Монастырь",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Выращивайте общие грибные сады и сочетайте древние монастырские традиции с пышным спороношением.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.3,
    plays: 6576000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-05",
    title: "Картографы Углей",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Картографируйте живой вулканический архипелаг, занимая маршруты до нового извержения.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.4,
    plays: 6713000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-06",
    title: "Маскарад Лунного Ключа",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Разгадывайте скрытые мотивы, обменивайтесь изящными уликами и раскройте тайного хозяина вечера.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.5,
    plays: 6850000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-07",
    title: "Механический Караван",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Развивайте странствующий механический рынок, торгуя деталями и проводя автоматонов через зыбучие дюны.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.6,
    plays: 6987000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-08",
    title: "Рифовые Гонщики",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Мчитесь по живому рифу, соединяя ловкие заплывы и собирая жемчуг до смены прилива.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.7,
    plays: 7124000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "board-09",
    title: "Шепчущие Колодцы",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Распределяйте драгоценную воду между селениями и слушайте колодцы, предсказывающие завтрашний дождь.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.8,
    plays: 7261000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-10",
    title: "Авроральная Кузница",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Создавайте светящиеся изобретения из полярных минералов, ловя идеальные краски северного неба.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.9,
    plays: 7398000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-11",
    title: "Сад Эха",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description: "Возрождайте забытую общину, складывая осколки памяти в сады общих историй.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.1,
    plays: 7535000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-12",
    title: "Скворцы-Стражи",
    category: "Настольные",
    tags: ["настольные", "новая игра"],
    description:
      "Координируйте строй стаи, защищая гнездовье и превращая метеорные потоки в сияющие ресурсы.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.2,
    plays: 7672000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-01",
    title: "Атлас Разломов",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Наносите на карту движущиеся острова, связывайте тактические карты и прокладывайте путь сквозь живую межпространственную бурю.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.3,
    plays: 7809000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-02",
    title: "Зелёный Пакт",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Ведите переговоры с древними духами растений и выращивайте лесной союз умными комбинациями карт.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.4,
    plays: 7946000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-03",
    title: "Контур Кинцуги",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Восстанавливайте цифровые реликвии светящимися швами и перехитряйте соперников-хакеров в городе карт.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.5,
    plays: 8083000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-04",
    title: "Лунный Зверинец",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Дружите с фантастическими зверями, удерживайте их настроение и устраивайте смелые побеги с живой колодой.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.6,
    plays: 8220000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-05",
    title: "Латунный Парламент",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Принимайте изобретательные законы, создавайте механические коалиции и свергайте соперничающие кабинеты картами дебатов.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.7,
    plays: 8357000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-06",
    title: "Армада Приливного Стекла",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Командуйте хрупким глубоководным флотом, собирайте живые рифы и обходите левиафанов приливными картами.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.8,
    plays: 8494000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-07",
    title: "Алхимия Углей",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Соединяйте нестабильные карты углей в чудесные зелья, пока лаборатория не поглотила саму себя.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.9,
    plays: 8631000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-08",
    title: "Небесный Ткацкий Станок",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Сплетайте погодные фронты и воздушные мосты в небесное королевство с помощью карт-узоров.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.1,
    plays: 8768000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-09",
    title: "Паром Фонарей",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Проводите странствующие души через меняющиеся болота, тратя карты воспоминаний для поиска безопасных путей.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.2,
    plays: 8905000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-10",
    title: "Каменоломня Гигантов",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Добывайте невозможные минералы, пробуждайте горных стражей и создавайте растущую колоду из живого камня.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.3,
    plays: 9042000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-11",
    title: "Хроматическая Осада",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Рисуйте защитников из ничего, меняйте цвета поля боя и возвращайте город одной яркой картой за другой.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.4,
    plays: 9179000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-12",
    title: "Курьер Авроры",
    category: "Карточные",
    tags: ["карточные", "новая игра"],
    description:
      "Доставляйте хрупкие магические послания через ледяные рубежи, оптимизируя маршруты картами курьера.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.5,
    plays: 9316000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-01",
    title: "Туманная кузница",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Куйте живую звезду сияющими ударами и постепенно расширяйте свою орбитальную мастерскую.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 9453000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "clicker-02",
    title: "Хранитель приливов",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Пробудите океанский жемчужный двигатель, усиливайте приливы и восстановите забытое царство рифов.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 9590000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-03",
    title: "Моховая клятва",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Выращивайте зачарованный мох и превращайте тайную пещеру в процветающий миниатюрный лес.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 9727000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-04",
    title: "Механический сад",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Заводите хитроумные деревья, собирайте механические плоды и автоматизируйте сад на энергии рассвета.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.9,
    plays: 9864000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-05",
    title: "Пастух гроз",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Собирайте дикую молнию, разводите сияющих грозовых змеев и управляйте погодой небесных островов.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.1,
    plays: 10001000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-06",
    title: "Реестр фонарей",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Заносите блуждающие духи-фонари в каталог и открывайте новые залы бесконечного ночного архива.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.2,
    plays: 10138000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-07",
    title: "Пыльцевый паломник",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Разносите редкую пыльцу между гигантскими цветами и пробудите долину чудесных растений.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 10275000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-08",
    title: "Ныряльщик рун",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Добывайте звучащие руны в затонувших руинах и соберите под сиянием полярного света магический двигатель.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 10412000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-09",
    title: "Искровой курьер",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Доставляйте искровые заряды через опасные каньоны, превращая двигатель феникса в пылающий флот.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.5,
    plays: 10549000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-10",
    title: "Картограф снов",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Картографируйте спящие сознания, соединяйте их созвездия и создайте общий мегаполис снов.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 10686000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-11",
    title: "Фермер лунных семян",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Сажайте лунные семена на дрейфующих астероидах, собирайте звёздный урожай и развивайте тихое космическое ранчо.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 10823000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-12",
    title: "Каменщик эха",
    category: "Кликеры",
    tags: ["кликеры", "новая игра"],
    description:
      "Превращайте звук в высокие сооружения и каждым ритмичным ударом создавайте живой город каньона.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 10960000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-01",
    title: "Солнечная Вуаль",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Мчитесь на сияющем купе по зеркальным каньонам, превращая каждый прыжок в солнечный тактический срез.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.9,
    plays: 11097000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-02",
    title: "Бегун Корней",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Проведите крошечного электробука по живым корням и собирайте энергию светлячков, открывая тайные тропы.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.1,
    plays: 11234000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-03",
    title: "Кольцевой Тягач",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Удерживайте скорость и груз, доставляя светящийся лёд по меняющимся дорогам колец Сатурна.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.2,
    plays: 11371000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-04",
    title: "Небесный Тариф",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Перевозите необычных пассажиров по вертикальному городу, осваивая shortcuts сквозь дождь, трафик и рои дронов.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.3,
    plays: 11508000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-05",
    title: "Дюнный След",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Режьте магнитные дюны, соединяйте прыжки на ветру и обгоняйте соперников под двойным рассветом.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.4,
    plays: 11645000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-06",
    title: "Грозовое Послание",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Доставляйте зачарованные посылки сквозь грозовое небо, прокладывая путь между молниями и облачными храмами.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.5,
    plays: 11782000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "driving-07",
    title: "Приливная Погоня",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Управляйте рифовым катером в затопленном метро, преследуя маяк, раскрывающий забытую карту океана.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.6,
    plays: 11919000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-08",
    title: "Дикий Меридиан",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Сопровождайте сияющие стада через опасную саванну, бережно расходуя солнечный заряд и сохраняя путь миграции.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.7,
    plays: 12056000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-09",
    title: "Морозная Кузня",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Пробивайте путь через сверхъестественные сугробы, улучшая снегоротор, чтобы спасти отрезанную горную деревню.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.8,
    plays: 12193000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-10",
    title: "Бег Углей",
    category: "Гонки",
    tags: ["гонки", "новая игра"],
    description:
      "Мчитесь по извергающемуся острову и спасайте светящихся детёнышей, пока лава не перекрыла пути отхода.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.9,
    plays: 12330000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-01",
    title: "Мохостражи",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Станьте ловким моховым духом, собирайте споры и перерастайте соперников на живой сети корней.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.1,
    plays: 12467000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-02",
    title: "Углепарусники",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Управляйте пылающим челноком в меняющихся лавовых протоках и争итесь за самые мощные вулканические течения.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.2,
    plays: 12604000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-03",
    title: "Кузнецы облаков",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Куйте грозовые машины в небесах и выпускайте созданные молниемёты против соперников-кузнецов.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.3,
    plays: 12741000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-04",
    title: "Приливное стекло",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Проводите сияющих медуз через хрупкие рифы, управляя течениями и формациями в подводной арене.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.4,
    plays: 12878000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-05",
    title: "Рельсовые гонщики",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Мчитесь по магнитным рельсам, на ходу меняйте полосы и похищайте энерго-грузы раньше соперников.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.5,
    plays: 13015000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-06",
    title: "Лунные мотыльки",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Порхайте между кратерными садами, собирайте редкую лунную пыльцу и перехитрите мотыльков-соперников.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.6,
    plays: 13152000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-07",
    title: "Призматическая нора",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Ройте разветвлённые тоннели, устраивайте засады снизу и захватывайте звенящие жеоды до смены пещеры.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.7,
    plays: 13289000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-08",
    title: "Ледяная кузня",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Толкайте живые ледяные монументы в зоны очков, замораживайте пути и разрушайте строй врагов.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.8,
    plays: 13426000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-09",
    title: "Фонарики-огоньки",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Несите светящиеся семена через болота, прокладывая безопасные пути, пока огоньки-соперники мешают росту рощи.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.9,
    plays: 13563000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-10",
    title: "Чернильный риф",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Рисуйте территорию чернилами и меняйте течения, стирая рифовые картины соперников в тёмной воде.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.1,
    plays: 13700000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-11",
    title: "Рой солнечных жуков",
    category: ".io",
    tags: [".io", "новая игра"],
    description:
      "Взбирайтесь на гигантские солнечные часы, направляйте свет роем и запирайте соперников в движущихся тенях.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.2,
    plays: 13837000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-01",
    title: "Настройщик прилива",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description:
      "Настраивайте приливные кольца, чтобы провести жемчужины через живой коралловый лабиринт.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 13974000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-02",
    title: "Скованный мхом",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Распутывайте корневые сети, чтобы пробудить забытого лесного хранителя.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 14111000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "puzzle-03",
    title: "Заводной сад",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Собирайте узоры из механических плодов, возвращая времена года парящему саду.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.5,
    plays: 14248000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-04",
    title: "Картограф углей",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description:
      "Прокладывайте меняющиеся угольные пути, соединяя разрозненные вулканические маяки.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 14385000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-05",
    title: "Облачные узлы",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Завязывайте и распускайте ленты бурь, соединяя острова в небесной вышине.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 14522000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "puzzle-06",
    title: "Хор фонарей",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description:
      "Составляйте световые гармонии, открывая безопасные проходы под затопленным собором.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 14659000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-07",
    title: "Пробуждение окаменелостей",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Восстанавливайте узоры древних панцирей, пробуждая подземную экосистему.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.9,
    plays: 14796000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-08",
    title: "Бархатное хранилище",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Выстраивайте порядок зачарованных ящиков, чтобы выбраться из безмолвного театра.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.1,
    plays: 14933000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "puzzle-09",
    title: "Лунное семя",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Подбирайте лунные семена к почвам кратеров, выращивая созвездие садов.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.2,
    plays: 15070000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-10",
    title: "Чернильные острова",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description:
      "Складывайте нарисованные волны, соединяя острова и спасая существ из живой карты.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 15207000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-11",
    title: "Ткацкий станок Авроры",
    category: "Головоломки",
    tags: ["головоломки", "новая игра"],
    description: "Переплетайте сияющие полосы в верном порядке, возвращая рассвет полярному краю.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 15344000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-01",
    title: "Бездна: Залп",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Погружайтесь в бездну и отбивайтесь от стай дронов гарпунными залпами среди затонувших руин.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.5,
    plays: 15481000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-02",
    title: "Пустынный контур",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description: "Мчитесь на ховербайке по пустыне и расстреливайте песчаных налётчиков на ходу.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.6,
    plays: 15618000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "shooting-03",
    title: "Лунная кузня",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Добывайте сияющие лунные кристаллы и сражайтесь с роями бронированных жуков под землёй.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.7,
    plays: 15755000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-04",
    title: "Протокол кроны",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Защитите живое поселение на деревьях, превращая семенные капсулы в скоростное оружие против пробудившихся лоз.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.8,
    plays: 15892000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-05",
    title: "Полярный груз",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Охраняйте парящий грузовой поезд, отбивая магнитных налётчиков из сияющих облаков.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.9,
    plays: 16029000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "shooting-06",
    title: "Хор углей",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Проводите взрывные звуковые волны через вулканические руины, подавляя духов пепла в ритме.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.1,
    plays: 16166000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-07",
    title: "Приливное стекло",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Преломляйте лучи маяка на затопленных улицах, заставляя гигантских штормовых зверей отступить в море.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.2,
    plays: 16303000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-08",
    title: "Моховой свет",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Выращивайте сияющие грибные сады и отстреливайте заводных жуков под лесным пологом.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.3,
    plays: 16440000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "shooting-09",
    title: "Раскол облаков",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Управляйте боевым аэростатом среди небесных островов и перестреливайте пиратов на электрических бурях.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.4,
    plays: 16577000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-10",
    title: "Эхо-хранилище",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Используйте резонансное оружие, чтобы выжить в музее, где статуи меняют позиции после каждого выстрела.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.5,
    plays: 16714000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-11",
    title: "Ледяная вспышка",
    category: "Стрелялки",
    tags: ["стрелялки", "новая игра"],
    description:
      "Освещайте ледяные тоннели сигнальными зарядами и охотьтесь на светящихся мотыльков под полярным сиянием.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.6,
    plays: 16851000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-01",
    title: "Тайдрайт",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Проектируйте приливные турбины, восстанавливайте рифы и удерживайте плавучую гавань в равновесии с переменчивой погодой.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.7,
    plays: 16988000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-02",
    title: "Эмберхайв",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Разводите сияющих жаростойких пчёл, настраивайте вулканические ульи и собирайте редкий мёд, не опаляя остров.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.8,
    plays: 17125000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-03",
    title: "Картограф облаков",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Запускайте метеозонды, прогнозируйте штормовые коридоры и прокладывайте безопасные воздушные маршруты по планете живой погоды.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.9,
    plays: 17262000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-04",
    title: "Моссбаунд",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Возрождайте забытые террасы, выращивая выносливый мох, направляя дождевую воду и возвращая жизнь разрушенной долине.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.1,
    plays: 17399000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-05",
    title: "Ночная развязка",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Планируйте магнитные грузовые составы, перераспределяйте энергию и снабжайте неоновый мегаполис до рассвета.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.2,
    plays: 17536000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-06",
    title: "Хор глубин",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Настраивайте сонарные гармонии, находите затонувшие корабли, поднимайте артефакты и берегите хрупкую экосистему глубин.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.3,
    plays: 17673000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-07",
    title: "Небесный сад",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Выращивайте фрукты на дрейфующих островах, балансируйте воздушные потоки и отправляйте урожай облачным поселениям.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.4,
    plays: 17810000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-08",
    title: "Ателье сияния",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Создавайте живые северные сияния, калибруйте хрустальные механизмы и устраивайте захватывающие представления полярного света.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.5,
    plays: 17947000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-09",
    title: "Хранитель кальдеры",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Следите за сейсмикой, направляйте геотермальную энергию и защищайте островные деревни от беспокойного вулкана.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.6,
    plays: 18084000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-10",
    title: "Курьеры кроны",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Прокладывайте смелые маршруты на планерах, доставляйте важные семена и соединяйте сообщества над кронами дождевого леса.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.7,
    plays: 18221000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-11",
    title: "Лунная усадьба",
    category: "Симуляторы",
    tags: ["симуляторы", "новая игра"],
    description:
      "Превращайте лунную пыль в плодородную почву, поддерживайте жизнеобеспечение и выращивайте самодостаточную колонию.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.8,
    plays: 18358000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-01",
    title: "Неоновые кайты",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Гоняйте на светящихся кайтах по меняющимся воздушным трассам, выполняя рискованные виражи над крышами.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.9,
    plays: 18495000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-02",
    title: "Ледяной свип",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Направляйте зачарованные камни по хрустальному льду, рассчитывая углы, трение и внезапные метели.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.1,
    plays: 18632000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-03",
    title: "Облачный прыжок",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Перепрыгивайте между парящими островами, точно рассчитывая прыжки, которые каждый раз меняют маршрут.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.2,
    plays: 18769000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "sports-04",
    title: "Ралли в бездне",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Обгоняйте соперников в глубоководной гонке сквозь рифы, шлюзы давления и неукротимые течения.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.3,
    plays: 18906000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-05",
    title: "Угольная калитка",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Отбивайте пылающие подачи мимо стихийных игроков и набирайте победный счёт до извержения вулкана.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.4,
    plays: 19043000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-06",
    title: "Гравитационная подача",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Освойте объёмные волейбольные розыгрыши, где каждая подача изгибается под меняющейся искусственной гравитацией.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.5,
    plays: 19180000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-07",
    title: "Зелёный спуск",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Соединяйте смелые спуски по живым лесам, балансируя между скоростью, прыжками и разветвлёнными тропами.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.6,
    plays: 19317000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-08",
    title: "Импульсная рапира",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Парируйте и атакуйте в молниеносных поединках, где точный тайминг заряжает адаптивную рапиру.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.7,
    plays: 19454000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-09",
    title: "Лунная клюшка",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Планируйте невероятные удары в лунном гольфе, используя слабую гравитацию, кратеры и космический мусор.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.8,
    plays: 19591000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-10",
    title: "Аврора на коньках",
    category: "Спорт",
    tags: ["спорт", "новая игра"],
    description:
      "Мчитесь по ледяным трассам, держась за соперниками и набирая скорость в сияющих полярных потоках.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.9,
    plays: 19728000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-01",
    title: "Атлас Приливов",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Уравновешивайте островные города, перенаправляя течения, поднимая рифы и торгуя безопасными маршрутами.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 19865000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-02",
    title: "Споровый Караван",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Развивайте грибную экономику, где каждый вид караванов меняет производство, оборону и дипломатию.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 20002000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-03",
    title: "Грозовой Змей",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Расширяйте небесную федерацию, прокладывая воздушные пути, собирая штормы и переигрывая адмиралов-соперников.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 20139000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-04",
    title: "Монахи Солнечного Хранилища",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Отыщите погребённый солнечный двигатель, программируя шествия монахов, снабжение и точные раскопки.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 20276000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-05",
    title: "Сад Авроры",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Выращивайте живые сады-авроры, укрывайте экспедиции, меняйте ледовые маршруты и опережайте полярных соперников.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 20413000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-06",
    title: "Союз Крыш",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Объединяйте голубиные гильдии срочными договорами, курьерскими маршрутами и рискованной игрой на крышах.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 20550000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-07",
    title: "Рубеж Солнечных Ульев",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Защищайте солнечные ульи и каньонные поселения, совершенствуя сети опыления против адаптивных машин.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.7,
    plays: 20687000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-08",
    title: "Зеркальные Пилигримы",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Ведите дома зеркальных паломников по меняющемуся озеру, балансируя веру, ресурсы и небесные прогнозы.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.8,
    plays: 20824000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-09",
    title: "Лавовый Ткацкий Станок",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Формируйте вулканический рубеж, выстраивая русла лавы, укрепляя заставы и предсказывая извержения.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.9,
    plays: 20961000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-10",
    title: "Кузня Кельпа",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Восстанавливайте затонувшее святилище с помощью логистики дронов, рифовой инженерии и бережного управления кислородом.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 21098000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "strategy-11",
    title: "Магнитный Пастух",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Направляйте магнитную погоду вокруг турбин, превращая атмосферные узоры в энергию, укрытия и влияние.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 21235000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-12",
    title: "Каменный Сад",
    category: "Стратегии",
    tags: ["стратегии", "новая игра"],
    description:
      "Пробуждайте каменных гигантов и растите живое царство каньонов переговорами, орошением и сезонным планированием.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 21372000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-01",
    title: "Атлас фонарей",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description: "Разгадывайте подсказки о погибших цивилизациях и зажигайте атлас забытых мест.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 21509000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-02",
    title: "Пилот пульса",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Проходите ритмичные цепочки вопросов в космических гонках, заряжая корабль каждым верным ответом.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 21646000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-03",
    title: "Сад шёпота",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Определяйте самые необычные виды природы и выращивайте живое убежище из правильных ответов.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 21783000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-04",
    title: "Бездонное течение",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Погружайтесь в историю океана и раскрывайте морские тайны, пока течение не унесло экспедицию.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.7,
    plays: 21920000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-05",
    title: "Механический суд",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Допрашивайте причудливых механических свидетелей, чтобы раскрывать исторические дела в медном суде.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.8,
    plays: 22057000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-06",
    title: "Облачный картограф",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Изучайте географию, погоду и достопримечательности, пока воздушная экспедиция опережает бурю.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.9,
    plays: 22194000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-07",
    title: "Пепельный архив",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Восстанавливайте осколки прошлого, отвечая на вопросы об искусстве, науке и памяти человечества.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 22331000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-08",
    title: "Лунный базар",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Обменивайте знания на невозможные сокровища, узнавая культуры, изобретения и диковинки со всего мира.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 22468000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-09",
    title: "Призматический тигель",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Решайте задачи по химии и физике, стабилизируя зрелищные реакции до перегрева печи.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 22605000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-10",
    title: "Каньон эха",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Используйте звуковые подсказки и общие знания, чтобы пройти каньон, который всё помнит.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 22742000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-11",
    title: "Ледяной рубеж",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Выживайте в полярной экспедиции, изучая климат, животных, исследования и небесные явления.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 22879000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-12",
    title: "Кольцо чудес",
    category: "Викторины",
    tags: ["викторины", "новая игра"],
    description:
      "Отвечайте на вопросы обо всём, открывайте номера и создавайте самое незабываемое шоу чудес.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 23016000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-01",
    title: "Глифовая роща",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description: "Проведите ловкую лису через живой лес, восстанавливая узоры сломанных глифов.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.7,
    plays: 23153000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-02",
    title: "Неоновый кочевник",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Восстанавливайте сбитые сигналы, пока курьер мчится по городу, меняющему собственную планировку.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.8,
    plays: 23290000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-03",
    title: "Прилив гласных",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Составляйте цепочки гласных, чтобы успокоить разумный океан и открыть маршруты к затонувшим островам.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.9,
    plays: 23427000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "word-04",
    title: "Риф шифров",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Расшифровывайте последовательности раковин, помогая осьминогу исследовать меняющееся глубоководное убежище.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.1,
    plays: 23564000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-05",
    title: "Ткацкий стан букв",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Сплетайте совпадающие нити букв, чтобы восстановить созвездия и вернуть ночное небо.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.2,
    plays: 23701000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-06",
    title: "Осада слогов",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description: "Собирайте слоги в защитные заклинания, прежде чем буря сотрёт цитадель.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.3,
    plays: 23838000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-07",
    title: "Реликвия загадок",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Разгадайте многоуровневые пустынные загадки, чтобы пробудить реликвию, отмечающую забытые цивилизации.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.4,
    plays: 23975000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-08",
    title: "Словокит",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Составляйте слова на лету, направляя небесного кита сквозь штормы к тайным облачным гаваням.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.5,
    plays: 24112000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-09",
    title: "Чернильный алхимик",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Смешивайте языковые ингредиенты в точные названия, меняющие магический эффект каждого зелья.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.6,
    plays: 24249000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-10",
    title: "Карнавал согласных",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Выстраивайте кристаллы согласных в ритмичные узоры, чтобы странствующий карнавал оставался в воздухе.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.7,
    plays: 24386000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-11",
    title: "Ледяной лексикон",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Стройте связанные словесные пути по льду, пока ледник не запечатал маршрут экспедиции.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.8,
    plays: 24523000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-12",
    title: "Кузня фраз",
    category: "Слова",
    tags: ["слова", "новая игра"],
    description:
      "Закаляйте осколки фраз в мощные чары для ворона-кузнеца, охраняющего вулканическую кузню.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.9,
    plays: 24660000,
    year: 2026,
    accent: "coral",
  },
];

export const categories: Category[] = [
  "Экшен",
  "Приключения",
  "Аркадные",
  "Настольные",
  "Карточные",
  "Кликеры",
  "Гонки",
  ".io",
  "Головоломки",
  "Стрелялки",
  "Симуляторы",
  "Спорт",
  "Стратегии",
  "Викторины",
  "Слова",
];
export const formatPlays = (value: number) =>
  value >= 1_000_000
    ? `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)} млн`
    : `${Math.round(value / 1000)} тыс.`;
