import racingImage from "@/assets/game-racing.jpg";
import actionImage from "@/assets/game-action.jpg";
import puzzleImage from "@/assets/game-puzzle.jpg";
import ioImage from "@/assets/game-io.jpg";
import neonRiptideImage from "@/assets/cover-action-neon-riptide.jpg";
import emberVaultImage from "@/assets/cover-action-ember-vault.jpg";
import skyhookImage from "@/assets/cover-action-skyhook.jpg";
import mossbladeImage from "@/assets/cover-action-mossblade.jpg";
import prismaticSiegeImage from "@/assets/cover-action-prismatic-siege.jpg";
import driftingLanternImage from "@/assets/cover-action-drifting-lantern.jpg";
export type Category =
  | "Экшен"
  | "Приключения"
  | "Аркадные"
  | "Настольные"
  | "Карточные"
  | "Кликеры"
  | "Гонки"
  | ".io"
  | "Головоломки"
  | "Стрелялки"
  | "Симуляторы"
  | "Спорт"
  | "Стратегии"
  | "Викторины"
  | "Слова";

export type Game = {
  slug: string;
  title: string;
  category: Category;
  tags: string[];
  description: string;
  controls: string[];
  image: string;
  rating: number;
  plays: number;
  year: number;
  badge?: "ХИТ" | "НОВОЕ" | "ТОП";
  accent: "lime" | "cyan" | "coral";
};

export const games: Game[] = [
  {
    slug: "neon-drift",
    title: "Neon Drift",
    category: "Гонки",
    tags: ["машины", "дрифт", "3D"],
    description:
      "Ночные заезды по неоновому мегаполису. Дрифтуйте в миллиметрах от соперников и собирайте нитро.",
    controls: ["WASD — движение", "Пробел — ручной тормоз", "Shift — нитро"],
    image: racingImage,
    rating: 4.9,
    plays: 12800000,
    year: 2026,
    badge: "ХИТ",
    accent: "lime",
  },
  {
    slug: "skyline-raider",
    title: "Skyline Raider",
    category: "Приключения",
    tags: ["паркур", "экшен", "герой"],
    description:
      "Покоряйте летающий город с крюком-кошкой и пробирайтесь через головокружительные уровни.",
    controls: ["WASD — движение", "Мышь — прицел", "E — крюк"],
    image: actionImage,
    rating: 4.8,
    plays: 7600000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "prism-shift",
    title: "Prism Shift",
    category: "Головоломки",
    tags: ["логика", "порталы", "блоки"],
    description:
      "Меняйте гравитацию, соединяйте кристаллы и открывайте порталы в футуристической лаборатории.",
    controls: ["Мышь — выбор", "R — перезапуск", "Z — отмена"],
    image: puzzleImage,
    rating: 4.7,
    plays: 4200000,
    year: 2026,
    badge: "ТОП",
    accent: "cyan",
  },
  {
    slug: "hover-arena",
    title: "Hover Arena",
    category: ".io",
    tags: ["мультиплеер", "арена", "гонки"],
    description:
      "Соревнуйтесь на воздушных аренах, сталкивайте соперников и останьтесь последним пилотом.",
    controls: ["WASD — движение", "Мышь — камера", "Пробел — ускорение"],
    image: ioImage,
    rating: 4.6,
    plays: 9100000,
    year: 2026,
    badge: "ХИТ",
    accent: "coral",
  },
  {
    slug: "strike-point",
    title: "Strike Point",
    category: "Стрелялки",
    tags: ["FPS", "тактика", "онлайн"],
    description:
      "Быстрые тактические матчи на компактных аренах с точной стрельбой и мгновенным стартом.",
    controls: ["WASD — движение", "Мышь — прицел", "R — перезарядка"],
    image: actionImage,
    rating: 4.5,
    plays: 6500000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "turbo-league",
    title: "Turbo League",
    category: "Спорт",
    tags: ["футбол", "машины", "аркада"],
    description:
      "Футбол на реактивных машинах: забивайте с воздуха и защищайте ворота вместе с командой.",
    controls: ["Стрелки — движение", "X — прыжок", "C — ускорение"],
    image: racingImage,
    rating: 4.7,
    plays: 5900000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "block-bloom",
    title: "Block Bloom",
    category: "Аркадные",
    tags: ["блоки", "релакс", "комбо"],
    description: "Собирайте сияющие фигуры в линии и создавайте длинные цепочки комбо без таймера.",
    controls: ["Мышь — перемещение", "Клик — разместить", "Esc — пауза"],
    image: puzzleImage,
    rating: 4.4,
    plays: 3800000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "zero-zone",
    title: "Zero Zone",
    category: "Экшен",
    tags: ["выживание", "арена", "волны"],
    description: "Отбивайтесь от волн дронов, комбинируйте оружие и продержитесь до эвакуации.",
    controls: ["WASD — движение", "Мышь — атака", "1–3 — оружие"],
    image: ioImage,
    rating: 4.6,
    plays: 8100000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "circuit-sprint",
    title: "Circuit Sprint",
    category: "Гонки",
    tags: ["скорость", "тайм-атак", "аркада"],
    description: "Короткие техничные трассы, призрачные соперники и борьба за сотые доли секунды.",
    controls: ["WASD — движение", "Shift — нитро", "R — рестарт"],
    image: racingImage,
    rating: 4.3,
    plays: 2700000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "portal-paws",
    title: "Portal Paws",
    category: "Приключения",
    tags: ["платформер", "головоломка", "кот"],
    description:
      "Помогите космическому коту вернуться домой, прыгая между измерениями и собирая звёзды.",
    controls: ["Стрелки — движение", "Пробел — прыжок", "E — портал"],
    image: puzzleImage,
    rating: 4.8,
    plays: 3400000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "goal-rush",
    title: "Goal Rush",
    category: "Спорт",
    tags: ["футбол", "пенальти", "быстрая"],
    description: "Серия пенальти с идеальной физикой удара. Читайте вратаря и попадайте в девятку.",
    controls: ["Мышь — направление", "Удержание — сила", "Пробел — удар"],
    image: ioImage,
    rating: 4.2,
    plays: 2100000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "pixel-frontier",
    title: "Pixel Frontier",
    category: "Симуляторы",
    tags: ["крафт", "исследование", "пиксели"],
    description: "Исследуйте уютный бесконечный мир, собирайте ресурсы и стройте собственную базу.",
    controls: ["WASD — движение", "Мышь — действие", "I — инвентарь"],
    image: actionImage,
    rating: 4.5,
    plays: 4700000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-01",
    title: "Неоновый Прибой",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: neonRiptideImage,
    rating: 4.4,
    plays: 1781000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-02",
    title: "Пепельный Свод",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: emberVaultImage,
    rating: 4.5,
    plays: 1918000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-03",
    title: "Небесный Крюк",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: skyhookImage,
    rating: 4.6,
    plays: 2055000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "action-04",
    title: "Моховой Клинок",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: mossbladeImage,
    rating: 4.7,
    plays: 2192000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-05",
    title: "Призматическая Осада",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: prismaticSiegeImage,
    rating: 4.8,
    plays: 2329000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-06",
    title: "Дрейфующий Фонарь",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: driftingLanternImage,
    rating: 4.9,
    plays: 2466000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "action-07",
    title: "Железный Сад",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.1,
    plays: 2603000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-08",
    title: "Бегущий Сквозь Завесу",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.2,
    plays: 2740000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "action-09",
    title: "Приливная Кузня",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.3,
    plays: 2877000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "action-10",
    title: "Солнечная Спираль",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.4,
    plays: 3014000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "action-11",
    title: "Цветочный Контур",
    category: "Экшен",
    tags: ["экшен"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — движение", "Мышь — действие"],
    image: actionImage,
    rating: 4.5,
    plays: 3151000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-01",
    title: "Картограф приливного стекла",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.6,
    plays: 3288000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-02",
    title: "Сад углей",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.7,
    plays: 3425000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-03",
    title: "Кочевник лунной магистрали",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.8,
    plays: 3562000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-04",
    title: "Эхо-фонарь",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.9,
    plays: 3699000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-05",
    title: "Воздушный змей морозного ветра",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.1,
    plays: 3836000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-06",
    title: "Пробуждение корней",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.2,
    plays: 3973000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-07",
    title: "Заводная крачка",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.3,
    plays: 4110000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "adventure-08",
    title: "Призматическое хранилище",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.4,
    plays: 4247000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "adventure-09",
    title: "Пыльный хор",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.5,
    plays: 4384000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "adventure-10",
    title: "Хранители мохового света",
    category: "Приключения",
    tags: ["приключения"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение", "Пробел — действие"],
    image: actionImage,
    rating: 4.6,
    plays: 4521000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-01",
    title: "Облачный курьер",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.7,
    plays: 4658000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-02",
    title: "Жемчужный захват",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.8,
    plays: 4795000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "arcade-03",
    title: "Ветровая спираль",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.9,
    plays: 4932000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-04",
    title: "Искра шестерён",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.1,
    plays: 5069000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-05",
    title: "Приливный прыгун",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.2,
    plays: 5206000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "arcade-06",
    title: "Грозовой звон",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.3,
    plays: 5343000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-07",
    title: "Скользящий полярный свет",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.4,
    plays: 5480000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-08",
    title: "Солнечный перекат",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.5,
    plays: 5617000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "arcade-09",
    title: "Ловец угольков",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.6,
    plays: 5754000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "arcade-10",
    title: "Орбитальный сад",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.7,
    plays: 5891000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "arcade-11",
    title: "Призматическое крыло",
    category: "Аркадные",
    tags: ["аркадные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь / касание — играть"],
    image: puzzleImage,
    rating: 4.8,
    plays: 6028000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-01",
    title: "Совет Приливного Стекла",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.9,
    plays: 6165000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-02",
    title: "Фонарный Сад",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.1,
    plays: 6302000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-03",
    title: "Железные Воздушные Змеи",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.2,
    plays: 6439000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-04",
    title: "Моховой Монастырь",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.3,
    plays: 6576000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-05",
    title: "Картографы Углей",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.4,
    plays: 6713000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-06",
    title: "Маскарад Лунного Ключа",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.5,
    plays: 6850000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-07",
    title: "Механический Караван",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.6,
    plays: 6987000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-08",
    title: "Рифовые Гонщики",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.7,
    plays: 7124000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "board-09",
    title: "Шепчущие Колодцы",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.8,
    plays: 7261000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "board-10",
    title: "Авроральная Кузница",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.9,
    plays: 7398000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "board-11",
    title: "Сад Эха",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.1,
    plays: 7535000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "board-12",
    title: "Скворцы-Стражи",
    category: "Настольные",
    tags: ["настольные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ход"],
    image: puzzleImage,
    rating: 4.2,
    plays: 7672000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-01",
    title: "Атлас Разломов",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.3,
    plays: 7809000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-02",
    title: "Зелёный Пакт",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.4,
    plays: 7946000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-03",
    title: "Контур Кинцуги",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.5,
    plays: 8083000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-04",
    title: "Лунный Зверинец",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.6,
    plays: 8220000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-05",
    title: "Латунный Парламент",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.7,
    plays: 8357000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-06",
    title: "Армада Приливного Стекла",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.8,
    plays: 8494000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-07",
    title: "Алхимия Углей",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.9,
    plays: 8631000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-08",
    title: "Небесный Ткацкий Станок",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.1,
    plays: 8768000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-09",
    title: "Паром Фонарей",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.2,
    plays: 8905000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "card-10",
    title: "Каменоломня Гигантов",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.3,
    plays: 9042000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "card-11",
    title: "Хроматическая Осада",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.4,
    plays: 9179000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "card-12",
    title: "Курьер Авроры",
    category: "Карточные",
    tags: ["карточные"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать карту"],
    image: puzzleImage,
    rating: 4.5,
    plays: 9316000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-01",
    title: "Туманная кузница",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 9453000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "clicker-02",
    title: "Хранитель приливов",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 9590000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-03",
    title: "Моховая клятва",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 9727000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-04",
    title: "Механический сад",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.9,
    plays: 9864000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-05",
    title: "Пастух гроз",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.1,
    plays: 10001000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-06",
    title: "Реестр фонарей",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.2,
    plays: 10138000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-07",
    title: "Пыльцевый паломник",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 10275000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-08",
    title: "Ныряльщик рун",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 10412000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-09",
    title: "Искровой курьер",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.5,
    plays: 10549000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "clicker-10",
    title: "Картограф снов",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 10686000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "clicker-11",
    title: "Фермер лунных семян",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 10823000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "clicker-12",
    title: "Каменщик эха",
    category: "Кликеры",
    tags: ["кликеры"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клик — собирать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 10960000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-01",
    title: "Солнечная Вуаль",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.9,
    plays: 11097000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-02",
    title: "Бегун Корней",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.1,
    plays: 11234000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-03",
    title: "Кольцевой Тягач",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.2,
    plays: 11371000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-04",
    title: "Небесный Тариф",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.3,
    plays: 11508000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-05",
    title: "Дюнный След",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.4,
    plays: 11645000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-06",
    title: "Грозовое Послание",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.5,
    plays: 11782000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "driving-07",
    title: "Приливная Погоня",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.6,
    plays: 11919000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "driving-08",
    title: "Дикий Меридиан",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.7,
    plays: 12056000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "driving-09",
    title: "Морозная Кузня",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.8,
    plays: 12193000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "driving-10",
    title: "Бег Углей",
    category: "Гонки",
    tags: ["гонки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD — управление"],
    image: racingImage,
    rating: 4.9,
    plays: 12330000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-01",
    title: "Мохостражи",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.1,
    plays: 12467000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-02",
    title: "Углепарусники",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.2,
    plays: 12604000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-03",
    title: "Кузнецы облаков",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.3,
    plays: 12741000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-04",
    title: "Приливное стекло",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.4,
    plays: 12878000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-05",
    title: "Рельсовые гонщики",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.5,
    plays: 13015000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-06",
    title: "Лунные мотыльки",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.6,
    plays: 13152000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-07",
    title: "Призматическая нора",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.7,
    plays: 13289000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-08",
    title: "Ледяная кузня",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.8,
    plays: 13426000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "io-09",
    title: "Фонарики-огоньки",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.9,
    plays: 13563000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "io-10",
    title: "Чернильный риф",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.1,
    plays: 13700000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "io-11",
    title: "Рой солнечных жуков",
    category: ".io",
    tags: [".io"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD / мышь — управление"],
    image: ioImage,
    rating: 4.2,
    plays: 13837000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-01",
    title: "Настройщик прилива",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 13974000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-02",
    title: "Скованный мхом",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 14111000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "puzzle-03",
    title: "Заводной сад",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.5,
    plays: 14248000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-04",
    title: "Картограф углей",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.6,
    plays: 14385000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-05",
    title: "Облачные узлы",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.7,
    plays: 14522000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "puzzle-06",
    title: "Хор фонарей",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.8,
    plays: 14659000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-07",
    title: "Пробуждение окаменелостей",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.9,
    plays: 14796000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-08",
    title: "Бархатное хранилище",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.1,
    plays: 14933000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "puzzle-09",
    title: "Лунное семя",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.2,
    plays: 15070000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "puzzle-10",
    title: "Чернильные острова",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.3,
    plays: 15207000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "puzzle-11",
    title: "Ткацкий станок Авроры",
    category: "Головоломки",
    tags: ["головоломки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать"],
    image: puzzleImage,
    rating: 4.4,
    plays: 15344000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-01",
    title: "Бездна: Залп",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.5,
    plays: 15481000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-02",
    title: "Пустынный контур",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.6,
    plays: 15618000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "shooting-03",
    title: "Лунная кузня",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.7,
    plays: 15755000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-04",
    title: "Протокол кроны",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.8,
    plays: 15892000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-05",
    title: "Полярный груз",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.9,
    plays: 16029000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "shooting-06",
    title: "Хор углей",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.1,
    plays: 16166000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-07",
    title: "Приливное стекло",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.2,
    plays: 16303000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-08",
    title: "Моховой свет",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.3,
    plays: 16440000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "shooting-09",
    title: "Раскол облаков",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.4,
    plays: 16577000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "shooting-10",
    title: "Эхо-хранилище",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.5,
    plays: 16714000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "shooting-11",
    title: "Ледяная вспышка",
    category: "Стрелялки",
    tags: ["стрелялки"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["WASD + мышь — прицел"],
    image: actionImage,
    rating: 4.6,
    plays: 16851000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-01",
    title: "Тайдрайт",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.7,
    plays: 16988000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-02",
    title: "Эмберхайв",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.8,
    plays: 17125000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-03",
    title: "Картограф облаков",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.9,
    plays: 17262000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-04",
    title: "Моссбаунд",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.1,
    plays: 17399000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-05",
    title: "Ночная развязка",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.2,
    plays: 17536000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-06",
    title: "Хор глубин",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.3,
    plays: 17673000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-07",
    title: "Небесный сад",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.4,
    plays: 17810000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-08",
    title: "Ателье сияния",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.5,
    plays: 17947000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "simulation-09",
    title: "Хранитель кальдеры",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.6,
    plays: 18084000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "simulation-10",
    title: "Курьеры кроны",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.7,
    plays: 18221000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "simulation-11",
    title: "Лунная усадьба",
    category: "Симуляторы",
    tags: ["симуляторы"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — взаимодействие"],
    image: actionImage,
    rating: 4.8,
    plays: 18358000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-01",
    title: "Неоновые кайты",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.9,
    plays: 18495000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-02",
    title: "Ледяной свип",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.1,
    plays: 18632000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-03",
    title: "Облачный прыжок",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.2,
    plays: 18769000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "cyan",
  },
  {
    slug: "sports-04",
    title: "Ралли в бездне",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.3,
    plays: 18906000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-05",
    title: "Угольная калитка",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.4,
    plays: 19043000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-06",
    title: "Гравитационная подача",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.5,
    plays: 19180000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-07",
    title: "Зелёный спуск",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.6,
    plays: 19317000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "sports-08",
    title: "Импульсная рапира",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.7,
    plays: 19454000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "sports-09",
    title: "Лунная клюшка",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.8,
    plays: 19591000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "sports-10",
    title: "Аврора на коньках",
    category: "Спорт",
    tags: ["спорт"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Стрелки — движение"],
    image: ioImage,
    rating: 4.9,
    plays: 19728000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-01",
    title: "Атлас Приливов",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 19865000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-02",
    title: "Споровый Караван",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 20002000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-03",
    title: "Грозовой Змей",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 20139000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-04",
    title: "Монахи Солнечного Хранилища",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 20276000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-05",
    title: "Сад Авроры",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 20413000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-06",
    title: "Союз Крыш",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 20550000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-07",
    title: "Рубеж Солнечных Ульев",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.7,
    plays: 20687000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "strategy-08",
    title: "Зеркальные Пилигримы",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.8,
    plays: 20824000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-09",
    title: "Лавовый Ткацкий Станок",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.9,
    plays: 20961000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "strategy-10",
    title: "Кузня Кельпа",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 21098000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "lime",
  },
  {
    slug: "strategy-11",
    title: "Магнитный Пастух",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 21235000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "strategy-12",
    title: "Каменный Сад",
    category: "Стратегии",
    tags: ["стратегии"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать приказ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 21372000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-01",
    title: "Атлас фонарей",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 21509000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-02",
    title: "Пилот пульса",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 21646000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-03",
    title: "Сад шёпота",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 21783000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-04",
    title: "Бездонное течение",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.7,
    plays: 21920000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-05",
    title: "Механический суд",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.8,
    plays: 22057000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-06",
    title: "Облачный картограф",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.9,
    plays: 22194000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-07",
    title: "Пепельный архив",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.1,
    plays: 22331000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-08",
    title: "Лунный базар",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.2,
    plays: 22468000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-09",
    title: "Призматический тигель",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.3,
    plays: 22605000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "trivia-10",
    title: "Каньон эха",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.4,
    plays: 22742000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "trivia-11",
    title: "Ледяной рубеж",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.5,
    plays: 22879000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "trivia-12",
    title: "Кольцо чудес",
    category: "Викторины",
    tags: ["викторины"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Мышь — выбрать ответ"],
    image: puzzleImage,
    rating: 4.6,
    plays: 23016000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-01",
    title: "Глифовая роща",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.7,
    plays: 23153000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-02",
    title: "Неоновый кочевник",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.8,
    plays: 23290000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-03",
    title: "Прилив гласных",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.9,
    plays: 23427000,
    year: 2026,
    badge: "НОВОЕ",
    accent: "coral",
  },
  {
    slug: "word-04",
    title: "Риф шифров",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.1,
    plays: 23564000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-05",
    title: "Ткацкий стан букв",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.2,
    plays: 23701000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-06",
    title: "Осада слогов",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.3,
    plays: 23838000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-07",
    title: "Реликвия загадок",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.4,
    plays: 23975000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-08",
    title: "Словокит",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.5,
    plays: 24112000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-09",
    title: "Чернильный алхимик",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.6,
    plays: 24249000,
    year: 2026,
    accent: "coral",
  },
  {
    slug: "word-10",
    title: "Карнавал согласных",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.7,
    plays: 24386000,
    year: 2026,
    accent: "lime",
  },
  {
    slug: "word-11",
    title: "Ледяной лексикон",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.8,
    plays: 24523000,
    year: 2026,
    accent: "cyan",
  },
  {
    slug: "word-12",
    title: "Кузня фраз",
    category: "Слова",
    tags: ["слова"],
    description: "Новая игра из расширенного каталога GameHaven.",
    controls: ["Клавиатура — вводить слова"],
    image: puzzleImage,
    rating: 4.9,
    plays: 24660000,
    year: 2026,
    accent: "coral",
  },
];

export const categories: Category[] = [
  "Экшен",
  "Приключения",
  "Аркадные",
  "Настольные",
  "Карточные",
  "Кликеры",
  "Гонки",
  ".io",
  "Головоломки",
  "Стрелялки",
  "Симуляторы",
  "Спорт",
  "Стратегии",
  "Викторины",
  "Слова",
];
export const formatPlays = (value: number) =>
  value >= 1_000_000
    ? `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)} млн`
    : `${Math.round(value / 1000)} тыс.`;
